Repository XdotRS/xrb, pull requests merged in 2023-01, with the labels that each got.

#33 Moved cornflakes to local `xrbk` crate
  Cargo.toml
  src/common.rs
  src/common/wrapper.rs
  src/connection.rs
  xrbk/Cargo.toml
  xrbk/src/datasize.rs
  xrbk/src/lib.rs
  xrbk/src/readable.rs
  xrbk/src/writable.rs
  xrbk_macro/src/attribute.rs
  xrbk_macro/src/definition/expansion/datasize.rs
  xrbk_macro/src/definition/expansion/readable.rs
  xrbk_macro/src/definition/expansion/trait.rs
  xrbk_macro/src/definition/expansion/writable.rs
  xrbk_macro/src/derive.rs
  xrbk_macro/src/element.rs
  xrbk_macro/src/element/expansion.rs
  xrbk_macro/src/element/expansion/xrbk.rs
  xrbk_macro/src/lib.rs
  xrbk_macro/src/source.rs
Labels: enhancement, task

#41 add common::WindowClass enum
  src/common.rs
Labels: task

#48 Provide default implementation of Request::length and Reply::length
  src/message.rs
Labels: documentation, task

#49 XRBK macro: implement Error message trait syntax
  src/x11/error.rs
  xrbk_macro/src/attribute.rs
  xrbk_macro/src/attribute/expansion.rs
  xrbk_macro/src/attribute/parsing.rs
  xrbk_macro/src/definition.rs
  xrbk_macro/src/definition/expansion.rs
  xrbk_macro/src/definition/expansion/readable.rs
  xrbk_macro/src/definition/expansion/trait.rs
  xrbk_macro/src/definition/expansion/writable.rs
  xrbk_macro/src/definition/expansion/x11_size.rs
  xrbk_macro/src/definition/parsing.rs
  xrbk_macro/src/element.rs
  xrbk_macro/src/element/iter.rs
  xrbk_macro/src/element/parsing.rs
Labels: task

#51 Implement X11 errors with the newly added XRBK macro Error syntax
  src/common.rs
  src/lib.rs
  src/message.rs
  src/x11/error.rs
Labels: task

#55 Fix some documentation mistakes in x11::error
  src/x11/error.rs
Labels: documentation

#61 Create CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#63 XRBK macro: syntax for Request::OtherErrors
  src/message.rs
  xrbk_macro/src/definition.rs
  xrbk_macro/src/definition/expansion.rs
  xrbk_macro/src/definition/expansion/message_trait.rs
  xrbk_macro/src/definition/expansion/writable.rs
  xrbk_macro/src/definition/parsing.rs
Labels: bug, task

#67 Rewrite XRB crate docs to match README.md
  README.md
  src/lib.rs
Labels: documentation

#70 XRBK macro: #[derive(Wrap)] so XRBK traits can be implemented for Options
  src/common.rs
  src/common/atom.rs
  xrbk/src/lib.rs
  xrbk_macro/src/derive.rs
  xrbk_macro/src/lib.rs
Labels: task

#69 Add wrapper enums.
  src/common.rs
  src/common/atom.rs
  src/common/wrapper.rs
  src/message.rs
  xrbk/src/lib.rs
  xrbk_macro/src/derive.rs
  xrbk_macro/src/lib.rs
Labels: task

#71 Delete old, outdated x11 modules
  src/x11/common/id/atoms.rs
  src/x11/common/id/mod.rs
  src/x11/common/mod.rs
  src/x11/common/string.rs
  src/x11/common/values.rs
  src/x11/common/wrappers.rs
  src/x11/requests/mod.rs
Labels: task

#75 Add assorted extra documentation
  src/common.rs
  src/common/atom.rs
  src/common/res_id.rs
  src/common/wrapper.rs
  src/connection.rs
  src/lib.rs
  src/message.rs
  src/x11.rs
  src/x11/event.rs
Labels: documentation

#77 Move visual-related types into new `common::visual`
  src/common.rs
  src/common/res_id.rs
  src/common/visual.rs
  src/connection.rs
  src/lib.rs
  src/x11/event.rs
Labels: task

#78 Implement window `Attributes`
  Cargo.toml
  src/common.rs
  src/common/attribute.rs
  src/common/mask.rs
  src/common/visual.rs
  src/common/wrapper.rs
  src/lib.rs
  src/x11/event.rs
  xrbk/src/lib.rs
  xrbk_macro/src/definition/expansion/message_trait.rs
Labels: task

#82 Add sets for `WindowConfigs`, `GraphicsOptions`, and `KeyboardOptions`
  src/common.rs
  src/common/set.rs
  src/common/set/attribute.rs
  src/common/set/graphics_options.rs
  src/common/set/keyboard_options.rs
  src/common/set/window_configs.rs
Labels: task

#86 Fixes, refinements, and documentation for sets
  src/common.rs
  src/common/mask.rs
  src/common/set.rs
  src/common/set/attribute.rs
  src/common/set/graphics_options.rs
  src/common/set/keyboard_options.rs
  src/common/set/window_configs.rs
  src/common/visual.rs
  src/common/wrapper.rs
  src/connection.rs
  src/lib.rs
  src/x11/event.rs
Labels: bug, documentation, enhancement, task

#89 Added units to represent things like pixels or millimeters
  src/common.rs
  src/common/atom.rs
  src/common/res_id.rs
  src/common/set.rs
  src/common/set/graphics_options.rs
  src/common/set/keyboard_options.rs
  src/common/set/window_configs.rs
  src/common/visual.rs
  src/lib.rs
  src/message.rs
  src/unit.rs
  src/x11/event.rs
Labels: enhancement, task

#90 Add options summary to `KeyboardOptions` and `WindowConfig`
  src/common/set.rs
  src/common/set/keyboard_options.rs
  src/common/set/window_config.rs
Labels: documentation, task

#64 XRBK macro: specify traits for `hide` attributes
  Cargo.toml
  src/x11/error.rs
  src/x11/event.rs
  xrbk_macro/src/attribute.rs
  xrbk_macro/src/attribute/expansion.rs
  xrbk_macro/src/attribute/parsing.rs
  xrbk_macro/src/element.rs
  xrbk_macro/src/element/expansion/xrbk.rs
  xrbk_macro/src/lib.rs
Labels: documentation, enhancement, help wanted

#94 Rename `Color` to `ColorId`
  src/common/set/attribute.rs
  src/common/set/graphics_options.rs
  src/common/visual.rs
  src/message.rs
Labels: task

#95 Update code style (attributes after doc comments)
  CONTRIBUTING.md
  src/common.rs
  src/connection.rs
  src/message.rs
  src/x11/error.rs
  src/x11/event.rs
Labels: documentation
